spring:
  profiles:
    active:
      - dev
      - email
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
---
spring:
  config:
    import: email.yml
    activate:
      on-profile: prod & email
